---
title: "Underlying Data"
date: "December 3, 2019"
output: html_document
---

<style>                     
.navbar {
  background-color:grey;
  border-color:black;
}
.navbar-brand {
color:black!important;
}
</style>  


```{r, message=F, warning=F, echo = FALSE}
#Load neccessary Libraries
library(dbplyr)
library(jsonlite)
#install.packages("xml2")
library(xml2)
library(readr)
#install.packages("readxl")
library(readxl)
library(sf)
library(ggplot2)
library(sf)
library(tidyverse)
#install.packages("spData")
library(spData)
#install.packages("maps")
library(maps)
library(formattable)
library(knitr)
library(kableExtra)
```

```{r, warning = FALSE, message = FALSE, echo = FALSE}
#Load in all of the DSIRE datasets
NREL_url <- "https://data.nrel.gov/files/114/NREL_Community_Solar_Project_List_6_28_2019%20FINAL.xlsx"
NREL_path <- "NREL_Community_Solar_Project_List_6_28_2019FINAL.xlsx"
NREL_Data <- read_xlsx(NREL_path, sheet = 2)
names(NREL_Data) <- c("Project", "City", "State", "Utility", "Size(kWh)","Year","Latitude", "Longitude")

Harvard_url <- "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/VOQCHQ/FQ9NBF"
Harvard_Data <- read_tsv(Harvard_url)

state_geom<- map_data("state")

DSIRE_program <- read_csv("https://raw.githubusercontent.com/geo511-2019/2019-geo511-project-austin3087/master/program.csv")
DSIRE_parameter_set <- read_csv("https://raw.githubusercontent.com/geo511-2019/2019-geo511-project-austin3087/master/parameter_set.csv")
DSIRE_parameter <- read_csv("https://raw.githubusercontent.com/geo511-2019/2019-geo511-project-austin3087/master/parameter.csv")
DSIRE_state <- read_csv("https://raw.githubusercontent.com/geo511-2019/2019-geo511-project-austin3087/master/state.csv")
names(DSIRE_state)<- c("state_id", "abbreviation", "name", "is_territory")
DSIRE_program_tech <- read_csv("https://raw.githubusercontent.com/geo511-2019/2019-geo511-project-austin3087/master/program_technology.csv")
DSIRE_technology <- read_csv("https://raw.githubusercontent.com/geo511-2019/2019-geo511-project-austin3087/master/technology.csv")
DSIRE_technology_category <- read_csv("https://raw.githubusercontent.com/geo511-2019/2019-geo511-project-austin3087/master/technology_category.csv")
```


```{r, warning = FALSE, message = FALSE, echo = FALSE}
#Join the DSIRE datasets by their relevant keys creating one "Final" table with relevant information. See data relationship chart above to identify how tables are related. 
DSIRE_program2 <- inner_join(DSIRE_program,DSIRE_state, by = "state_id")%>%
  inner_join(DSIRE_parameter_set, by = c("id" = "program_id"))%>%
  inner_join(DSIRE_parameter, by = c("id" = "parameter_set_id"))%>%
  inner_join(DSIRE_program_tech, by = c("id" = "program_id"))%>%
  inner_join(DSIRE_technology, by = c("technology_id" = "id"))
DSIRE_program_final <- inner_join(DSIRE_program2, DSIRE_technology_category, by = c("technology_id" = "id"))
```


```{r, warning = FALSE, echo = FALSE}
#Filter table for solar photovoltaics
DSIRE_program_table <- DSIRE_program_final%>%
  filter(is_entire_state == 1)%>%
  filter(name.x.x == "Solar Photovoltaics")%>%
  filter(is_territory == 0)
kwh_total_state <- DSIRE_program_table%>%
  group_by(name.y)%>%
   summarize(Total = n())
names(kwh_total_state)<- c("State","Total")
kwh_total_state$State <- tolower(kwh_total_state$State)

kwh_mean_state <- DSIRE_program_table%>%
  group_by(name.y)%>%
  filter(units == "$")%>% #note only using $ values that are given, multiple other units given too in table but needed to be filtered for this analysis
  summarize(Total = mean(amount))
names(kwh_mean_state)<- c("State", "Average")
kwh_mean_state$State <- tolower(kwh_mean_state$State)

```


```{r, warning = FALSE, echo = FALSE}

#Create Custom theme 
theme_black<- theme(plot.background = element_rect(fill = '#121212'), panel.background = element_rect(fill = '#121212'),panel.border = element_rect(fill = NA), panel.grid = element_line(color = '#121212'), axis.text.x = element_blank(), axis.text.y = element_blank(), legend.position = "none")


DSIRE_program_table1 <- full_join(kwh_total_state, state_geom, by = c("State" = "region"))

#Plot just Community Locationsadd state geometry to DSIRE data to plot
plot1 <- ggplot()+
  geom_polygon(data = state_geom, aes(x = long, y = lat, group = group ), fill = '#222222', col = "#ba5454")+
  coord_fixed(ratio = 1.2)+
  geom_point(NREL_Data, mapping = aes(x = Longitude , y = Latitude, alpha = .85), col = "#6ca2b8")+
  theme(plot.background = element_rect(fill = '#222222'), panel.background = element_rect(fill = NA),panel.border = element_rect(fill = NA), panel.grid = element_line(color = NA), axis.title = element_blank(), legend.position = "none", plot.margin = unit(c(0,0,0,0),"cm"), axis.text = element_blank(), axis.line = element_blank())
```


```{r, warning = FALSE, echo = FALSE}
DSIRE_program_table2 <- full_join(kwh_mean_state, state_geom, by = c("State" = "region"))

plot2 <- ggplot()+
  geom_polygon(data = DSIRE_program_table2, aes(x = long, y = lat, group = group, fill = Average), col = "blue")+
  coord_fixed(1.5)+
  geom_point(NREL_Data, mapping = aes(x = Longitude , y = Latitude, col = "red", alpha = .8))+
  theme_void()
```

```{r, warning = FALSE, echo = FALSE}
DSIRE_program_table3 <- full_join(kwh_total_state, state_geom, by = c("State" = "region"))

plot3 <- ggplot()+
  geom_polygon(data = DSIRE_program_table3, aes(x = long, y = lat, group = group, col = "blue", fill = Total))+
  coord_fixed(1.5)+
  geom_point(NREL_Data, mapping = aes(x = Longitude , y = Latitude, col = "red", alpha = .8))+
  theme_void()+
  scale_fill_gradient(low = "#496692", high = "#000E23")
```





#Underlying Data 
##Two tables displaying the data used in the report. 

***

##Raw Data 
Show the total amount of power generated per state (kWh) 
```{r, fig.width=8, fig.height=4, fig.cap="Map of completely random data", echo = FALSE, warning = FALSE}
library("DT")
kwh_total_state_table<- kwh_total_state%>%
  group_by(State)%>%
  arrange(desc(Total))

datatable(kwh_total_state_table)%>%
  formatStyle(columns = c(" ","State", "Total"),color = 'black')
```

Show the mean size of community solar installations (kWh) 
```{r, fig.width=8, fig.height=4, echo = FALSE, warning = FALSE}
#install.packages("DT")
library(DT)
kwh_mean_state_table<- kwh_mean_state%>%
  arrange(desc(Average))

datatable(kwh_mean_state_table)%>%
  formatStyle(columns = c(" ","State", "Average"),color = 'black')
```                 